= asciidoctor-gb

image:https://img.shields.io/gem/v/asciidoctor-gb.svg["Gem Version", link="https://rubygems.org/gems/asciidoctor-gb"]
image:https://img.shields.io/travis/riboseinc/asciidoctor-gb/master.svg["Build Status", link="https://travis-ci.org/riboseinc/asciidoctor-gb"]
image:https://codeclimate.com/github/riboseinc/asciidoctor-gb/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/asciidoctor-gb"]

Gem for generating https://en.wikipedia.org/wiki/Guobiao_standards[Guibiao standards]
(Chinese national standards), using Asciidoc. This gem inherits from 
https://github.com/riboseinc/asciidoctor-iso, a gem used to generate ISO standards
using Asciidoc. The two standards formats are closely aligned.

== Differences from asciidoctor-iso

=== Document Attributes

`:title-intro-zh:, :title-main-zh:, :title-part-zh:`:: These are the title introduction, main title, and part title in Chinese. (They replace their French counterparts in asciidoctor-iso.)
`:technical-committee-type:`:: The type of the technical committee (`technical` or `provisional`).
`:equivalence:`:: The relation of the GB standard to a corresponding ISO standard (`equivalent`, `identical`, `nonequivalent`).
`:scope:`:: The scope of the GB standard (`national`, `sector`, `professional`, `local`, `enterprise`).
`:mandate:`:: The mandate of the GB standard (`mandatory`, `recommended`, `guidelines`).
`:prefix:`:: The prefix classifying the GB standard.
`:published-date`:: The date on which the GB standard was published.
`:activated-date`:: The date on which the GB standard was activated.
